name: Open link daily

on:
  schedule:
    # 8:00 PM IST = 14:30 UTC
    - cron: '41 13 * * *'
  workflow_dispatch:

jobs:
  open-link:
    runs-on: ubuntu-latest
    steps:
      - name: Open the link
        run: |
          curl -L https://erp.silicon.ac.in/estcampus/hostel/db_hostel_attendance.php?oper=CHECK_HOSTEL_ATTENDANCE&studentId=23BCSD42

  
